### ISSUE TITLE
Provide a name via UI

### ISSUE THREAD

**Issue by daniviga** [gem/oq-consolidate#1]
If the consolidate project does not exist yet it is created by the plugin with the name `project.qgs`.

It should be possible for the user to provide a custom name via UI.

**Comment by ptormene** [comment]
Partially fixed in https://github.com/gem/oq-consolidate/pull/6

**Comment by ptormene** [comment]
Still TODO:

- [x] improve layout (the new widgets should be inserted on top instead of on the bottom)
- [x] slugify project name (or at least strip spaces, to make it suitable for a file name)
