### ISSUE TITLE
Copy geopackages

### ISSUE THREAD

**Issue by daniviga** [gem/oq-consolidate#15]
If a source data is already in geopackage format we should just copy and re-link it, not reconverting it (to save time).

**Comment by ptormene** [comment]
Copying a geopackage is not trivial (see https://sqlite.org/wal.html). Therefore, for now, we are just adding a TODO.

**Comment by daniviga** [comment]
Since performance of exporting GeoPackage is fairly good I would skip this at all and always re-export data instead of copying gpkg files. This will save us from lot of headaches
